### ISSUE TITLE
Crash opening features with lots of xlink:href

### ISSUE THREAD

**Issue by JPPauly** [qgisinspiretools/qgis-wfs20-client-plugin#19]
Hello,
on loading features with lots of xlink:href elements with the resolve option activated, f.e. from INSPIRE AU.AdministrativeUnits, QGIS3 crashes. 

Example-service that leads to crashes on loading AdministrativeUnits: https://www.geodaten-mv.de/dienste/inspire_au_atkis_bdlm_download

I found a solution by changing the line 1010 in wfsclientdialog.py to: `gdal.SetConfigOption('GML_SKIP_RESOLVE_ELEMS', 'HUGE')`

**Comment by ejn** [comment]
Thanks for the report. Looking at https://gdal.org/drivers/vector/gml.html#gml-xlink-resolving then setting `GML_SKIP_RESOLVE_ELEMS` to `HUGE` should work in all cases.

I wonder whether there any disadvantages to it? I guess a slight overhead in saving resolved objects to DB rather than keeping them in memory, but any others?

Maybe it would be better to allow the user to choose between `ALL`, `HUGE` AND `NONE` in the configuration dialog in case there are some special cases where one or the other is necessary?

**Comment by ejn** [comment]
It seems that there are no disadvantages to using `HUGE` ([source](https://lists.osgeo.org/pipermail/gdal-dev/2020-May/052203.html)), so I'll just change it as you suggest.

**Comment by JPPauly** [comment]
Thank you for fixing the issue. 

Are there any plans to deploy those fixes to the QGIS Plugin repository's version of the plugin? That would make rollout easier in our organisation.

**Comment by ejn** [comment]
@JPPauly Thanks for the feedback. To be honest I'd completely forgotten that this hadn't been done - I'll see to it, that the repo version gets updated and close this ticket once it's done.

**Comment by ejn** [comment]
Plugin version 0.9.10 is now published and approved in the QGIS Plugins repository.
